### PR TITLE
[*] Update wording blocknewsletter.php

### PR DESCRIPTION
**Pull request by Nobodaddy**

### CODE REVIEW

**Comment by maximebiloe** [comment]
Hello,

Thanks for your contribution.
Could you make your PR on `dev` branch, please ? Because `master` is the stable one.

Thanks in advance.

**Comment by Nobodaddy** [comment]
Which I did 2 days ago when I recognized it was the wrong branch:
https://github.com/Nobodaddy/blocknewsletter/commit/e72a73dd5c01f31adf641f9cb0ee0902ecd454d2

**Comment by maximebiloe** [comment]
You PR was on `master` branch and you don't have a PR opened on `dev` one.

**Comment by Nobodaddy** [comment]
Ok, forget it!

**Pull request closed without merging**
